# coding: utf-8

"""
    TV-API

    The TVAPI Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.metacritic_review_detail import MetacriticReviewDetail  # noqa: E501
from swagger_client.rest import ApiException


class TestMetacriticReviewDetail(unittest.TestCase):
    """MetacriticReviewDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetacriticReviewDetail(self):
        """Test MetacriticReviewDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.metacritic_review_detail.MetacriticReviewDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
